// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent_service.proto

package agentservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType - Type of streaming message
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Progress message (stdout line from AI)
	MessageType_MESSAGE_TYPE_PROGRESS MessageType = 1
	// Error message (stderr line)
	MessageType_MESSAGE_TYPE_ERROR MessageType = 2
	// System message (process started, etc.)
	MessageType_MESSAGE_TYPE_SYSTEM MessageType = 3
	// Final result with full output
	MessageType_MESSAGE_TYPE_RESULT MessageType = 4
	// Task started message (contains task_id)
	MessageType_MESSAGE_TYPE_TASK_STARTED MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_PROGRESS",
		2: "MESSAGE_TYPE_ERROR",
		3: "MESSAGE_TYPE_SYSTEM",
		4: "MESSAGE_TYPE_RESULT",
		5: "MESSAGE_TYPE_TASK_STARTED",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_PROGRESS":     1,
		"MESSAGE_TYPE_ERROR":        2,
		"MESSAGE_TYPE_SYSTEM":       3,
		"MESSAGE_TYPE_RESULT":       4,
		"MESSAGE_TYPE_TASK_STARTED": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_service_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_agent_service_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

// ExecuteRequest - Request to execute an AI task
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User prompt to send to AI (required)
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Unique identifier for this execution, used for cancellation and message routing (required)
	SenderId string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Working directory for the AI process (required)
	WorkingDir string `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// AI engine to use: "claude" or "gemini" (default: "claude")
	AiEngine string `protobuf:"bytes,4,opt,name=ai_engine,json=aiEngine,proto3" json:"ai_engine,omitempty"`
	// Optional: Session ID to resume a previous conversation (Claude's --resume)
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional: System prompt / context to prepend
	SystemPrompt string `protobuf:"bytes,6,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Optional: Additional environment variables for the subprocess
	ExtraEnv map[string]string `protobuf:"bytes,7,rep,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional: Execution configuration overrides
	Config        *ExecuteConfig `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteRequest) GetAiEngine() string {
	if x != nil {
		return x.AiEngine
	}
	return ""
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ExecuteRequest) GetExtraEnv() map[string]string {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

func (x *ExecuteRequest) GetConfig() *ExecuteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ExecuteConfig - Configuration for AI execution
type ExecuteConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout in minutes (default: 30)
	TimeoutMinutes int32 `protobuf:"varint,1,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	// Max conversation turns (default: 50)
	MaxTurns int32 `protobuf:"varint,2,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	// Allowed tools (empty means all allowed)
	AllowedTools []string `protobuf:"bytes,3,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	// Disallowed tools
	DisallowedTools []string `protobuf:"bytes,4,rep,name=disallowed_tools,json=disallowedTools,proto3" json:"disallowed_tools,omitempty"`
	// MCP config file path
	McpConfig     string `protobuf:"bytes,5,opt,name=mcp_config,json=mcpConfig,proto3" json:"mcp_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteConfig) Reset() {
	*x = ExecuteConfig{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteConfig) ProtoMessage() {}

func (x *ExecuteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteConfig.ProtoReflect.Descriptor instead.
func (*ExecuteConfig) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteConfig) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

func (x *ExecuteConfig) GetMaxTurns() int32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *ExecuteConfig) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

func (x *ExecuteConfig) GetDisallowedTools() []string {
	if x != nil {
		return x.DisallowedTools
	}
	return nil
}

func (x *ExecuteConfig) GetMcpConfig() string {
	if x != nil {
		return x.McpConfig
	}
	return ""
}

// ExecuteResponse - Streaming response from AI execution
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message type
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=agentservice.v1.MessageType" json:"type,omitempty"`
	// Message content (for PROGRESS, ERROR, SYSTEM types)
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Final result (only set when type is RESULT)
	Result *ExecuteResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Task ID (returned in first response, included in all subsequent responses)
	TaskId        string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ExecuteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteResponse) GetResult() *ExecuteResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// ExecuteResult - Final result of AI execution
type ExecuteResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full output from AI
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Session ID for resume (from Claude's --resume)
	// Use this in subsequent requests to continue the conversation
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Process exit code (0 = success)
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Execution duration in seconds
	DurationSeconds float64 `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Status: "completed", "failed", "cancelled", "timeout"
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Error message if status is "failed"
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResult) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ExecuteResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthRequest - Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

// HealthResponse - Health check response
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service status: "healthy" or "unhealthy"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Service version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Number of active processes
	ActiveProcesses int32 `protobuf:"varint,3,opt,name=active_processes,json=activeProcesses,proto3" json:"active_processes,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetActiveProcesses() int32 {
	if x != nil {
		return x.ActiveProcesses
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// ListTasksRequest - Request to list active tasks
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

// ListTasksResponse - Response with active tasks
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// TaskInfo - Information about an AI execution task
type TaskInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task ID (UUID)
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Sender ID (client identifier)
	SenderId string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// AI engine being used
	AiEngine string `protobuf:"bytes,3,opt,name=ai_engine,json=aiEngine,proto3" json:"ai_engine,omitempty"`
	// Working directory
	WorkingDir string `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Preview of the prompt (truncated)
	PromptPreview string `protobuf:"bytes,5,opt,name=prompt_preview,json=promptPreview,proto3" json:"prompt_preview,omitempty"`
	// Task status: "pending", "running", "completed", "failed", "cancelled", "timeout"
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Created time as Unix timestamp
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Started time as Unix timestamp (0 if not started)
	StartedAt     int64 `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TaskInfo) GetAiEngine() string {
	if x != nil {
		return x.AiEngine
	}
	return ""
}

func (x *TaskInfo) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *TaskInfo) GetPromptPreview() string {
	if x != nil {
		return x.PromptPreview
	}
	return ""
}

func (x *TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

// CancelTaskRequest - Request to cancel a task by task_id
type CancelTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task ID to cancel
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// CancelTaskResponse - Response from cancel task request
type CancelTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the cancellation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CancelBySenderRequest - Request to cancel a task by sender_id
type CancelBySenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender ID of the task to cancel
	SenderId      string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBySenderRequest) Reset() {
	*x = CancelBySenderRequest{}
	mi := &file_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBySenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBySenderRequest) ProtoMessage() {}

func (x *CancelBySenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBySenderRequest.ProtoReflect.Descriptor instead.
func (*CancelBySenderRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *CancelBySenderRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// CancelBySenderResponse - Response from cancel by sender request
type CancelBySenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the cancellation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBySenderResponse) Reset() {
	*x = CancelBySenderResponse{}
	mi := &file_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBySenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBySenderResponse) ProtoMessage() {}

func (x *CancelBySenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBySenderResponse.ProtoReflect.Descriptor instead.
func (*CancelBySenderResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *CancelBySenderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBySenderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\x0fagentservice.v1\"\x88\x03\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12\x1b\n" +
	"\tai_engine\x18\x04 \x01(\tR\baiEngine\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12#\n" +
	"\rsystem_prompt\x18\x06 \x01(\tR\fsystemPrompt\x12J\n" +
	"\textra_env\x18\a \x03(\v2-.agentservice.v1.ExecuteRequest.ExtraEnvEntryR\bextraEnv\x126\n" +
	"\x06config\x18\b \x01(\v2\x1e.agentservice.v1.ExecuteConfigR\x06config\x1a;\n" +
	"\rExtraEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\rExecuteConfig\x12'\n" +
	"\x0ftimeout_minutes\x18\x01 \x01(\x05R\x0etimeoutMinutes\x12\x1b\n" +
	"\tmax_turns\x18\x02 \x01(\x05R\bmaxTurns\x12#\n" +
	"\rallowed_tools\x18\x03 \x03(\tR\fallowedTools\x12)\n" +
	"\x10disallowed_tools\x18\x04 \x03(\tR\x0fdisallowedTools\x12\x1d\n" +
	"\n" +
	"mcp_config\x18\x05 \x01(\tR\tmcpConfig\"\xae\x01\n" +
	"\x0fExecuteResponse\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.agentservice.v1.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x126\n" +
	"\x06result\x18\x03 \x01(\v2\x1e.agentservice.v1.ExecuteResultR\x06result\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\"\xbc\x01\n" +
	"\rExecuteResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x94\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10active_processes\x18\x03 \x01(\x05R\x0factiveProcesses\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x12\n" +
	"\x10ListTasksRequest\"D\n" +
	"\x11ListTasksResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.agentservice.v1.TaskInfoR\x05tasks\"\xfb\x01\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1b\n" +
	"\tai_engine\x18\x03 \x01(\tR\baiEngine\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0eprompt_preview\x18\x05 \x01(\tR\rpromptPreview\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x15CancelBySenderRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\"L\n" +
	"\x16CancelBySenderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xaf\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MESSAGE_TYPE_PROGRESS\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x02\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x03\x12\x17\n" +
	"\x13MESSAGE_TYPE_RESULT\x10\x04\x12\x1d\n" +
	"\x19MESSAGE_TYPE_TASK_STARTED\x10\x052\xb7\x03\n" +
	"\fAgentService\x12N\n" +
	"\aExecute\x12\x1f.agentservice.v1.ExecuteRequest\x1a .agentservice.v1.ExecuteResponse0\x01\x12R\n" +
	"\tListTasks\x12!.agentservice.v1.ListTasksRequest\x1a\".agentservice.v1.ListTasksResponse\x12U\n" +
	"\n" +
	"CancelTask\x12\".agentservice.v1.CancelTaskRequest\x1a#.agentservice.v1.CancelTaskResponse\x12a\n" +
	"\x0eCancelBySender\x12&.agentservice.v1.CancelBySenderRequest\x1a'.agentservice.v1.CancelBySenderResponse\x12I\n" +
	"\x06Health\x12\x1e.agentservice.v1.HealthRequest\x1a\x1f.agentservice.v1.HealthResponseB:Z8github.com/Baoqi/agent-service-api/api/v1;agentservicepbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_service_proto_goTypes = []any{
	(MessageType)(0),               // 0: agentservice.v1.MessageType
	(*ExecuteRequest)(nil),         // 1: agentservice.v1.ExecuteRequest
	(*ExecuteConfig)(nil),          // 2: agentservice.v1.ExecuteConfig
	(*ExecuteResponse)(nil),        // 3: agentservice.v1.ExecuteResponse
	(*ExecuteResult)(nil),          // 4: agentservice.v1.ExecuteResult
	(*HealthRequest)(nil),          // 5: agentservice.v1.HealthRequest
	(*HealthResponse)(nil),         // 6: agentservice.v1.HealthResponse
	(*ListTasksRequest)(nil),       // 7: agentservice.v1.ListTasksRequest
	(*ListTasksResponse)(nil),      // 8: agentservice.v1.ListTasksResponse
	(*TaskInfo)(nil),               // 9: agentservice.v1.TaskInfo
	(*CancelTaskRequest)(nil),      // 10: agentservice.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),     // 11: agentservice.v1.CancelTaskResponse
	(*CancelBySenderRequest)(nil),  // 12: agentservice.v1.CancelBySenderRequest
	(*CancelBySenderResponse)(nil), // 13: agentservice.v1.CancelBySenderResponse
	nil,                            // 14: agentservice.v1.ExecuteRequest.ExtraEnvEntry
}
var file_agent_service_proto_depIdxs = []int32{
	14, // 0: agentservice.v1.ExecuteRequest.extra_env:type_name -> agentservice.v1.ExecuteRequest.ExtraEnvEntry
	2,  // 1: agentservice.v1.ExecuteRequest.config:type_name -> agentservice.v1.ExecuteConfig
	0,  // 2: agentservice.v1.ExecuteResponse.type:type_name -> agentservice.v1.MessageType
	4,  // 3: agentservice.v1.ExecuteResponse.result:type_name -> agentservice.v1.ExecuteResult
	9,  // 4: agentservice.v1.ListTasksResponse.tasks:type_name -> agentservice.v1.TaskInfo
	1,  // 5: agentservice.v1.AgentService.Execute:input_type -> agentservice.v1.ExecuteRequest
	7,  // 6: agentservice.v1.AgentService.ListTasks:input_type -> agentservice.v1.ListTasksRequest
	10, // 7: agentservice.v1.AgentService.CancelTask:input_type -> agentservice.v1.CancelTaskRequest
	12, // 8: agentservice.v1.AgentService.CancelBySender:input_type -> agentservice.v1.CancelBySenderRequest
	5,  // 9: agentservice.v1.AgentService.Health:input_type -> agentservice.v1.HealthRequest
	3,  // 10: agentservice.v1.AgentService.Execute:output_type -> agentservice.v1.ExecuteResponse
	8,  // 11: agentservice.v1.AgentService.ListTasks:output_type -> agentservice.v1.ListTasksResponse
	11, // 12: agentservice.v1.AgentService.CancelTask:output_type -> agentservice.v1.CancelTaskResponse
	13, // 13: agentservice.v1.AgentService.CancelBySender:output_type -> agentservice.v1.CancelBySenderResponse
	6,  // 14: agentservice.v1.AgentService.Health:output_type -> agentservice.v1.HealthResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		EnumInfos:         file_agent_service_proto_enumTypes,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
